version: '3.3'

services:
   api:
     image: fastdatascience/clinical_trial_risk:20230623214440_cf82f4e
     depends_on:
       - tika
     ports:
       - "8000:80"
     restart: always
     environment:
        DOWNLOAD_DIRECTORY: /downloads
        TIKA_SERVER_ENDPOINT: http://tika:9998


   tika:
     image: apache/tika:2.8.0.0-full
     ports:
       - "9998:9998"
     restart: always
