import re

import pycountry

demonym_to_country_code = {'ARUBAN': 'AW',
                           'AFGHAN': 'AF',
                           'ANGOLAN': 'AO',
                           'ANGUILLIAN': 'AI',
                           'ALBANIAN': 'AL',
                           'EMIRATI': 'AE',
                           'ARGENTINEAN': 'AR',
                           'ARMENIAN': 'AM',
                           'AMERICAN SAMOAN': 'AS',
                           'FRENCH': 'PM',
                           'ANTIGUAN': 'AG',
                           'BARBUDAN': 'AG',
                           'AUSTRALIAN': 'AU',
                           'AUSTRIAN': 'AT',
                           'AZERBAIJANI': 'AZ',
                           'BURUNDIAN': 'BI',
                           'BELGIAN': 'BE',
                           'BENINESE': 'BJ',
                           'BURKINABE': 'BF',
                           'BANGLADESHI': 'BD',
                           'BULGARIAN': 'BG',
                           'BAHRAINI': 'BH',
                           'BAHAMIAN': 'BS',
                           'BOSNIAN': 'BA',
                           'HERZEGOVINIAN': 'BA',
                           'BELARUSIAN': 'BY',
                           'BELIZEAN': 'BZ',
                           'BERMUDIAN': 'BM',
                           'BOLIVIAN': 'BO',
                           'BRAZILIAN': 'BR',
                           'BARBADIAN': 'BB',
                           'BRUNEIAN': 'BN',
                           'BHUTANESE': 'BT',
                           'MOTSWANA': 'BW',
                           'CENTRAL AFRICAN': 'CF',
                           'CANADIAN': 'CA',
                           'COCOS ISLANDER': 'CC',
                           'SWISS': 'CH',
                           'CHILEAN': 'CL',
                           'IVORIAN': 'CI',
                           'CAMEROONIAN': 'CM',
                           'CONGOLESE': 'CG',
                           'COOK ISLANDER': 'CK',
                           'COLOMBIAN': 'CO',
                           'COMORAN': 'KM',
                           'CAPE VERDIAN': 'CV',
                           'COSTA RICAN': 'CR',
                           'CUBAN': 'CU',
                           'CHRISTMAS ISLAND': 'CX',
                           'CAYMANIAN': 'KY',
                           'CYPRIOT': 'CY',
                           'CZECH': 'CZ',
                           'GERMAN': 'DE',
                           'DJIBOUTI': 'DJ',
                           'DOMINICAN': 'DO',
                           'DANISH': 'DK',
                           'ALGERIAN': 'DZ',
                           'ECUADOREAN': 'EC',
                           'EGYPTIAN': 'EG',
                           'ERITREAN': 'ER',
                           'SAHRAWI': 'EH',
                           'SPANISH': 'ES',
                           'ESTONIAN': 'EE',
                           'ETHIOPIAN': 'ET',
                           'FINNISH': 'FI',
                           'FIJIAN': 'FJ',
                           'FALKLAND ISLANDER': 'FK',
                           'FAROESE': 'FO',
                           'MICRONESIAN': 'FM',
                           'GABONESE': 'GA',
                           'BRITISH': 'GB',
                           'GEORGIAN': 'GE',
                           'CHANNEL ISLANDER': 'JE',
                           'GHANAIAN': 'GH',
                           'GIBRALTAR': 'GI',
                           'GUINEAN': 'GN',
                           'GUADELOUPIAN': 'GP',
                           'GAMBIAN': 'GM',
                           'GUINEA-BISSAUAN': 'GW',
                           'EQUATORIAL GUINEAN': 'GQ',
                           'GREEK': 'GR',
                           'GRENADIAN': 'GD',
                           'GREENLANDIC': 'GL',
                           'GUATEMALAN': 'GT',
                           'GUAMANIAN': 'GU',
                           'GUYANESE': 'GY',
                           'HEARD AND MCDONALD ISLANDER': 'HM',
                           'HONDURAN': 'HN',
                           'CROATIAN': 'HR',
                           'HAITIAN': 'HT',
                           'HUNGARIAN': 'HU',
                           'INDONESIAN': 'ID',
                           'MANX': 'IM',
                           'IRISH': 'IE',
                           'IRANIAN': 'IR',
                           'IRAQI': 'IQ',
                           'ICELANDER': 'IS',
                           'ISRAELI': 'IL',
                           'ITALIAN': 'IT',
                           'JAMAICAN': 'JM',
                           'JORDANIAN': 'JO',
                           'JAPANESE': 'JP',
                           'KAZAKHSTANI': 'KZ',
                           'KENYAN': 'KE',
                           'KIRGHIZ': 'KG',
                           'CAMBODIAN': 'KH',
                           'I-KIRIBATI': 'KI',
                           'KIRIBATI': 'KI',
                           'KITTIAN AND NEVISIAN': 'KN',
                           'SOUTH KOREAN': 'KR',
                           'KUWAITI': 'KW',
                           'LAOTIAN': 'LA',
                           'LEBANESE': 'LB',
                           'LIBERIAN': 'LR',
                           'LIBYAN': 'LY',
                           'SAINT LUCIAN': 'LC',
                           'LIECHTENSTEINER': 'LI',
                           'SRI LANKAN': 'LK',
                           'MOSOTHO': 'LS',
                           'LITHUANIAN': 'LT',
                           'LUXEMBOURGER': 'LU',
                           'LATVIAN': 'LV',
                           'MOROCCAN': 'MA',
                           'MONEGASQUE': 'MC',
                           'MOLDOVAN': 'MD',
                           'MALAGASY': 'MG',
                           'MALDIVAN': 'MV',
                           'MEXICAN': 'MX',
                           'MARSHALLESE': 'MH',
                           'MACEDONIAN': 'MK',
                           'MALIAN': 'ML',
                           'MALTESE': 'MT',
                           'MONGOLIAN': 'MN',
                           'AMERICAN': 'US',
                           'MOZAMBICAN': 'MZ',
                           'MAURITANIAN': 'MR',
                           'MONTSERRATIAN': 'MS',
                           'MAURITIAN': 'MU',
                           'MALAWIAN': 'MW',
                           'MALAYSIAN': 'MY',
                           'NAMIBIAN': 'NA',
                           'NEW CALEDONIAN': 'NC',
                           'NIGERIEN': 'NE',
                           'NORFOLK ISLANDER': 'NF',
                           'NIGERIAN': 'NG',
                           'NICARAGUAN': 'NI',
                           'NIUEAN': 'NU',
                           'DUTCH': 'NL',
                           'NORWEGIAN': 'SJ',
                           'NEPALESE': 'NP',
                           'NAURUAN': 'NR',
                           'NEW ZEALANDER': 'NZ',
                           'OMANI': 'OM',
                           'PAKISTANI': 'PK',
                           'PANAMANIAN': 'PA',
                           'PITCAIRN ISLANDER': 'PN',
                           'PERUVIAN': 'PE',
                           'FILIPINO': 'PH',
                           'PALAUAN': 'PW',
                           'PAPUA NEW GUINEAN': 'PG',
                           'POLISH': 'PL',
                           'PUERTO RICAN': 'PR',
                           'NORTH KOREAN': 'KP',
                           'PORTUGUESE': 'PT',
                           'PARAGUAYAN': 'PY',
                           'FRENCH POLYNESIAN': 'PF',
                           'QATARI': 'QA',
                           'ROMANIAN': 'RO',
                           'RUSSIAN': 'RU',
                           'RWANDAN': 'RW',
                           'SAUDI ARABIAN': 'SA',
                           'SUDANESE': 'SD',
                           'SENEGALESE': 'SN',
                           'SINGAPOREAN': 'SG',
                           'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDER': 'GS',
                           'SAINT HELENIAN': 'SH',
                           'SOLOMON ISLANDER': 'SB',
                           'SIERRA LEONEAN': 'SL',
                           'SALVADORAN': 'SV',
                           'SAMMARINESE': 'SM',
                           'SOMALI': 'SO',
                           'SOUTH SUDANESE': 'SS',
                           'SAO TOMEAN': 'ST',
                           'SURINAMER': 'SR',
                           'SLOVAK': 'SK',
                           'SLOVENE': 'SI',
                           'SWEDISH': 'SE',
                           'SWAZI': 'SZ',
                           'SEYCHELLOIS': 'SC',
                           'SYRIAN': 'SY',
                           'CHADIAN': 'TD',
                           'TOGOLESE': 'TG',
                           'THAI': 'TH',
                           'TADZHIK': 'TJ',
                           'TAJIK': 'TJ',
                           'TOKELAUAN': 'TK',
                           'TURKMEN': 'TM',
                           'EAST TIMORESE': 'TL',
                           'TONGAN': 'TO',
                           'TRINIDADIAN': 'TT',
                           'TUNISIAN': 'TN',
                           'TURKISH': 'TR',
                           'TUVALUAN': 'TV',
                           'TAIWANESE': 'TW',
                           'TANZANIAN': 'TZ',
                           'UGANDAN': 'UG',
                           'UKRAINIAN': 'UA',
                           'URUGUAYAN': 'UY',
                           'UZBEKISTANI': 'UZ',
                           'SAINT VINCENTIAN': 'VC',
                           'VENEZUELAN': 'VE',
                           'VIETNAMESE': 'VN',
                           'NI-VANUATU': 'VU',
                           'WALLIS AND FUTUNA ISLANDER': 'WF',
                           'SAMOAN': 'WS',
                           'YEMENI': 'YE',
                           'SOUTH AFRICAN': 'ZA',
                           'ZAMBIAN': 'ZM',
                           'ZIMBABWEAN': 'ZW'}

demonym_to_country = dict(
    [demonym, pycountry.countries.lookup(alpha_2)]
    for demonym, alpha_2 in demonym_to_country_code.items()
)

people = {"adults", "men", "women", "children", "infants", "toddlers", "sex workers",
          "communities", "community",
          "population",
          "males", "male adults", "females",
          "female adults", "individuals",
          "volunteers", "babies", "teenagers", "adolescents", "pregnant"}

country_pattern = "(" + "|".join(demonym_to_country_code) + ")"
people_pattern = "(" + "|".join(people) + ")"

demonym_regex = re.compile(f"(?i)\\b(?:{country_pattern}(?:s|\\s*{people_pattern}))\\b")


def find_demonyms(text: str) -> list:
    """
    Find the nationalities mentioned in the text that clearly refer to study subjects, e.g. Samoan males.
    :param text: the text of the protocol page
    :return: nationalities found as a list of tuples (PyCountry object and Match object).
    """
    country_matches = []

    matches = demonym_regex.finditer(text)
    for match in matches:
        matched_country = demonym_to_country[match.groups()[0].upper()]
        country_matches.append((matched_country, match))

    return country_matches
